/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: df7bf9571700cf368e9ebc28627b08f5)
interface __BaseEnv_Env {
	ROOM_CREATE_LIMITER: RateLimit;
	ROOM_LOOKUP_LIMITER: RateLimit;
	ASSETS: Fetcher;
	ALLOWED_ORIGINS: "http://localhost:5173,https://r00tmancer.github.io,https://harfiyen-gundem.r00tmancer.workers.dev";
	ROOM: DurableObjectNamespace<import("./index").GameRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GameRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}